# Site settings
title: State of the Map 2020
email: sotm@openstreetmap.org
description: "The global OpenStreetMap conference. July 4 - 5 July, 2020 online (was planed to take place in Cape Town, South Africa)."
url: "http://2020.stateofthemap.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: 'rgb(255, 184, 28)'
  primary-light: 'rgb(0, 119, 73)'
  links: '#000'
  links-light: '#333'
  links-white: '#333'
  text: '#030303'
  background-light: '#fff'
  text-light: '#fff'

# Settings for map tiles used in leaflet maps
map_tiles:
  url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
  attribution: '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
  maxZoom: 19

# Repo files to not include in built site
exclude:
  - Dockerfile*
  - docker-compose.*
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: /:title/
relative_permalinks: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:title/

plugins:
  - jekyll-gzip
  # - jekyll-brotli
